services:
  - type: web
    name: launch-performance-intelligence
    runtime: image
    plan: free
    region: ohi
    dockerfilePath: ./Dockerfile
    envVars:
      - key: RENDER
        value: true
      - key: PORT
        value: 10000
      - key: STREAMLIT_SERVER_PORT
        value: 10000
      - key: STREAMLIT_SERVER_ADDRESS
        value: 0.0.0.0
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: false
    healthCheckPath: /_stcore/health
    autoDeploy: true
